### ISSUE TITLE
lcopt don't show results_FORWAST_ 500 : Server Error

### ISSUE THREAD

**Issue by R2D2-ad** [pjamesjoyce/lcopt#79]
Hello to everyone!
I just set up the environment for lcopt, I launched it and make the example flowchart with the kettle.
I did step by step what is showed in the video, however when I click to analyze the results I get an error and no results.
I use the FORWAST database.
When I go back it works, i can see the flowchart, the parameter set but no results.
I attach a screenshot of the error.
![server_error](https://user-images.githubusercontent.com/32665075/124242361-850a5900-dad1-11eb-84b8-8bdf612a60dd.png)

I run python 3.8.5 and the browser is Google Chrome.
I also launched lcopt by opening the example as it is and still keep having the 'server error 500", no results. 

I would appreciate any help.
Thanks and best regards

**Comment by R2D2-ad** [comment]
I run python 3.8.5 and the browser is Google Chrome. I also launched lcopt opening the example as it is and still i keep having the 'server error 500", no results. I also get some tracebacks when i run the analysis (see below
![tracebacks (1)](https://user-images.githubusercontent.com/32665075/124245349-c4867480-dad4-11eb-8c00-27e9b0309cdf.png)
![tracebacks (2)](https://user-images.githubusercontent.com/32665075/124245354-c5b7a180-dad4-11eb-8d4a-e6ef59685823.png)
)

**Comment by R2D2-ad** [comment]
Hello again
So after unistall and re-install lcopt, I still have server 500 error and some tracebacks in the powershell listed as followed:

Traceback (most recent call last):
  File "C:\Users\x\anaconda3\envs\lcopt\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()

  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()

  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\lcopt\interact.py", line 884, in analysis
    self.modelInstance.analyse(item, item_code)
  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\lcopt\model.py", line 790, in analyse
    self.result_set = my_analysis.run_analyses(demand_item, demand_item_code, **self.analysis_settings)
  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\lcopt\analysis.py", line 184, in run_analyses
    'method_units': [bw2.methods[method]['unit'] for method in methods],
  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\lcopt\analysis.py", line 184, in <listcomp>
    'method_units': [bw2.methods[method]['unit'] for method in methods],
  File "C:\Users\xx\anaconda3\envs\lcopt\lib\site-packages\bw2data\serialization.py", line 145, in __getitem__
    return self.data[key]
KeyError: ('USEtox', 'human toxicity', 'total')

Is something wrong with the brightway2 set up?
I am new in all these , so any feedback is welcomed.
Thanks again.
